# Generated by Django 3.0.2 on 2020-01-29 23:35

from django.db import migrations, models
import django_enumfield.db.fields
import miio.data_types


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('body', models.TextField()),
                ('is_archived', models.BooleanField(default=False)),
                ('type', django_enumfield.db.fields.EnumField(enum=miio.data_types.CardType)),
            ],
        ),
    ]
